# Generated by Django 3.0.3 on 2020-05-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='active_quiz',
            field=models.BooleanField(default=False, verbose_name='Active/Inactive'),
        ),
    ]
