# Generated by Django 3.0.3 on 2020-08-26 22:16

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_active_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='active_quiz',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.IntegerField(blank=True, null=True)),
                ('response_data', jsonfield.fields.JSONField(null=True)),
                ('parent_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz')),
            ],
            options={
                'verbose_name_plural': 'Responses',
                'db_table': 'response',
            },
        ),
    ]
