# Generated by Django 3.0.3 on 2020-05-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20200525_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
