# Generated by Django 3.0.3 on 2020-06-12 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20200527_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 1, 45, 8, 396420), verbose_name='date created'),
        ),
    ]
